#!/bin/sh
#
# ufetch-gentoo - tiny system info for gentoo
#

## INFO

# user is already defined
HOST="$(hostname)"
OS='Gentoo Linux'
KERNEL="$(uname -sr)"
UPTIME="$(uptime -p | sed s:'up ':'':)"
PACKAGES="$(ls -d /var/db/pkg/*/* | wc -l)"
# shell is already defined
if [[ -z "$WM" ]]; then
	WM=$(tail -n 1 "$HOME/.xinitrc" | cut -d ' ' -f3)
fi

## DEFINE COLORS

rc=$(tput sgr0)   # reset
c0=$(tput setaf 0)  # black
c1=$(tput setaf 1)  # red
c2=$(tput setaf 2)  # green
c3=$(tput setaf 3)  # yellow
c4=$(tput setaf 4)  # blue
c5=$(tput setaf 5)  # magenta
c6=$(tput setaf 6)  # cyan
c7=$(tput setaf 7)  # white
bc=$(tput bold)   # bold

# you can change these
lc=${bc}${c5}			# labels
nc=${bc}${c5}			# user and hostname
tc=${bc}${c7}			# text
fc=${bc}${c5}			# first color

## OUTPUT

cat <<EOF

${fc}   (  )${rc}        ${nc}${USER}${rc}${tc}@${rc}${nc}${HOSTNAME}${rc}
${fc}     (   )${rc}     ${lc}OS:${rc}        ${tc}${OS}${rc}
${fc}  (   ) (${rc}      ${lc}KERNEL:${rc}    ${tc}${KERNEL}${rc}
${fc}   ) _   )${rc}     ${lc}UPTIME:${rc}    ${tc}${UPTIME}${rc}
${fc}    ( \_${rc}       ${lc}PACKAGES:${rc}  ${tc}${PACKAGES}${rc}
${fc}  _(_\ \)__${rc}    ${lc}SHELL:${rc}     ${tc}${SHELL}${rc}
${fc} (____\___))${rc}   ${lc}WM:${rc}        ${tc}${WM}${rc}

EOF
