#!/bin/sh
#
# ufetch - tiny system info for crux
#

## INFO

# user is already defined
HOST="$(hostname)"
OS="$(crux)"
KERNEL="$(uname -sr)"
UPTIME="$(uptime -p | sed s:"up "::)"
PACKAGES="$(pkginfo -i | wc -l)"
# shell is already defined
WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d " " -f2)"

## DEFINE COLORS

# probably don't change these
bc="$(tput bold)"	# bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"	# reset

# you can change these
lc="${bc}${c6}"		# labels
nc="${bc}${c6}"		# user and hostname
tc="${bc}${c7}"		# text
pc="${c6}"		# penguin

## OUTPUT

cat <<EOF

${pc}   (  )${rc}        ${nc}${USER}${rc}${tc}@${rc}${nc}${HOST}${rc}
${pc}     (   )${rc}     ${lc}OS:${rc}       ${tc}${OS}${rc}
${pc}  (   ) (${rc}      ${lc}KERNEL:${rc}   ${tc}${KERNEL}${rc}
${pc}   ) _   )${rc}     ${lc}UPTIME:${rc}   ${tc}${UPTIME}${rc}
${pc}    ( \_${rc}       ${lc}PACKAGES:${rc} ${tc}${PACKAGES}${rc}
${pc}  _(_\ \)__${rc}    ${lc}SHELL:${rc}    ${tc}${SHELL}${rc}
${pc} (____\___))${rc}   ${lc}WM:${rc}       ${tc}${WM}${rc}

EOF
